/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homepage;

/**
 *
 * @author Adarsh R Shukla
 */
public class homeframe extends javax.swing.JFrame {

    /**
     * Creates new form homeframe
     */
    public homeframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        frame = new javax.swing.JTabbedPane();
        student = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        teacher = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        home = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        query = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        jLabel18.setText("jLabel18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frame.setBackground(new java.awt.Color(0, 204, 255));
        frame.setPreferredSize(new java.awt.Dimension(1000, 700));

        student.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Click Here  to login  :");
        student.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        student.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 110, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Students Section");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 50));
        student.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 70));

        jList1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Machine Learning", "Java ", "Python", "Data Structure", "C++", "Block Chain", "Cyber Security", "Internet Of Things" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);

        student.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 270));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adarsh R Shukla\\Downloads\\home3.png")); // NOI18N
        jLabel30.setText("jLabel30");
        student.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 450, 350));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel31.setText("Click Here to Exit");
        student.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, -1, 50));

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setText("BYE BYE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        student.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 100, 30));

        frame.addTab("Student", student);

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("COURSES");
        content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("CSE");
        content.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel5.setText("JAVA");
        content.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel7.setText("PYTHON");
        content.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel8.setText("MACHINE LEARNING");
        content.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 110, 30));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel9.setText("BLOCK CHAIN");
        content.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel10.setText("DEEP LEARNING");
        content.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("ELECTRONICS");
        content.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 200, 20));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel12.setText("ANALOG ELECTRONICS");
        content.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel13.setText("DIGITAL ELECTRONICS");
        content.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel14.setText("SIGNAL AND SYSTEM");
        content.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel15.setText("DATA COMMUNICATION");
        content.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setText("MATHEMATICS");
        content.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, 30));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel17.setText("LINEAR ALGEBRA");
        content.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel19.setText("DIFFERETIAL CALCULUS");
        content.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel20.setText("INTEGRAL CALCULATION");
        content.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel21.setText("NUMERICAL ANALYSIS");
        content.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        frame.addTab("Content", content);

        teacher.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        teacher.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 280, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setText("Contact Us :");
        teacher.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setText("About Tutor:");
        teacher.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jList2.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ashish : 8299619827", "sameer :7607608938", "sameera : 9110031724 ", "virat     : 8989653265", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jList2ComponentHidden(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        teacher.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 190, 130));

        jList3.setBorder(javax.swing.BorderFactory.createTitledBorder("ABOUT"));
        jList3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "E-tutors teach, motivate and direct students while maintaining high interest and achievement.", " They should be able to effectively interact with different populations of students at a variety of academic levels.", " They guide students to improve their knowledge through media such as email, asynchronous discussion forums or chat rooms.", " They coach, assess and provide subject-matter expertise: they're experts but also motivators and even technical support people.", " They bring the subject up to date with online digital resources and make it much more accessible." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList3);

        teacher.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 940, -1));

        frame.addTab("About Us", teacher);

        home.setBackground(new java.awt.Color(255, 153, 153));
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("E-Tutor : Yes, You can Learn");
        home.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, 580, 60));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("CSE");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 3));
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        home.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 220, 40));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("MATHS");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        home.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 210, 40));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("ELECTRONICS");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 3));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        home.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 220, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adarsh R Shukla\\Downloads\\pro.jpg")); // NOI18N
        jLabel22.setText("jLabel22");
        home.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 650, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("=> B.Tech Courses");
        home.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 250, 60));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("=>B.Sc Courses");
        home.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 200, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("=>BCA Courses");
        home.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("=> BBA Courses");
        home.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        query.setColumns(20);
        query.setRows(5);
        query.setText("You can submit your  query here");
        query.setBorder(javax.swing.BorderFactory.createTitledBorder("QUERY PLEASE"));
        jScrollPane2.setViewportView(query);

        home.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 270, 150));

        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        home.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 90, 30));

        frame.addTab("Home", home);

        getContentPane().add(frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 620));

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            new loginform().setVisible(true);        // TODO add your handling code here:
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        new maths().setVisible(true); 
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       new cse().setVisible(true); 
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 new electronics().setVisible(true);                 // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         query.setText("Yuo have submitted your Query");
       
    }                                        

    private void jList2ComponentHidden(java.awt.event.ComponentEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
System.exit(0);        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel content;
    private javax.swing.JTabbedPane frame;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea query;
    private javax.swing.JPanel student;
    private javax.swing.JPanel teacher;
    // End of variables declaration                   
}
